### ISSUE TITLE
How to do multi-GPU trainings

### ISSUE THREAD

**Issue by SamuelSchmidgall** [flow-diffusion/flow-diffusion#1]
It was mentioned in the paper that the model was trained across 4 GPUs--how do I do this with the code?

Thanks,
Sam

**Comment by kbkbowo** [comment]
Hello! We used [accelerate](https://huggingface.co/docs/accelerate/index) to do multi-GPU training. 

To do this, you can first use this terminal command to specify your training setting (how many/which gpus to use, automatic mixed precision training ... )
```bash
accelerate config
```

After that, you can launch your training by
```bash
accelerate launch train_xxx.py (--arguments)
```

After entering the command above, the training should be launched with multiple gpus! 
Let me know if this helps!
Po-Chen

**Comment by SamuelSchmidgall** [comment]
Thanks!
