### ISSUE TITLE
Code for Creating Training Datasets of Metaworld 

### ISSUE THREAD

**Issue by devinluo27** [flow-diffusion/flow-diffusion#6]
Can you provide the scripts to generate videos for training the video diffusion models and the corresponding datasets used for training the checkpoints?

**Comment by AstroTheKat** [comment]
I am also interested in this! :)

**Comment by kbkbowo** [comment]
Hello, the dataset is released here
https://huggingface.co/Po-Chen/flowdiffusion/tree/main/datasets
